# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ba8ee378084423fbb131793505a5f83c4283a52118975cd4b73d7354b81be27168a2b45ec584b1bb543299a0511fd01b891d16038b725adb20bc0503e35a7a6

test:
  secret_key_base: 0980ae6adc6d02fb782e4fff2c2b2c56304e7c54443e8b2ff76b65de3f93794400cd67fbfd495153df77cd3f962f98a4131b094b9866371030f404691abc2a35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
